# Generated by Django 6.0.6 on 2026-06-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('ANALIZAR', 'Analizar imagen'), ('PROCESAR', 'Procesar residuo'), ('EXPORTAR', 'Exportar datos'), ('CREAR', 'Crear registro'), ('EDITAR', 'Editar registro'), ('ELIMINAR', 'Eliminar registro'), ('LOGIN', 'Iniciar sesión'), ('LOGOUT', 'Cerrar sesión'), ('SISTEMA', 'Evento del sistema')], max_length=20, verbose_name='Acción')),
                ('modulo', models.CharField(choices=[('clasificacion', 'Detección IA'), ('administracion', 'Administración'), ('historial', 'Historial'), ('reportes', 'Reportes'), ('recoleccion', 'Recolección'), ('usuarios', 'Usuarios')], max_length=30, verbose_name='Módulo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('objeto_id', models.IntegerField(blank=True, null=True, verbose_name='ID objeto')),
                ('objeto_tipo', models.CharField(blank=True, max_length=100, verbose_name='Tipo objeto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Entrada de Historial',
                'verbose_name_plural': 'Entradas de Historial',
                'ordering': ['-fecha'],
            },
        ),
    ]
