# Generated by Django 6.0.6 on 2026-06-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradahistorial',
            name='accion',
            field=models.CharField(choices=[('ANALIZAR', 'Analizar imagen'), ('PROCESAR', 'Procesar residuo'), ('EXPORTAR', 'Exportar datos'), ('CREAR', 'Crear registro'), ('EDITAR', 'Editar registro'), ('ELIMINAR', 'Eliminar registro'), ('ACEPTAR', 'Aceptar residuo'), ('RECHAZAR', 'Rechazar residuo'), ('PRECIO', 'Actualizar precio'), ('LOGIN', 'Iniciar sesión'), ('LOGOUT', 'Cerrar sesión'), ('SISTEMA', 'Evento del sistema')], max_length=20, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='entradahistorial',
            name='modulo',
            field=models.CharField(choices=[('clasificacion', 'Detección IA'), ('administracion', 'Administración'), ('contabilidad', 'Contabilidad'), ('historial', 'Historial'), ('reportes', 'Reportes'), ('usuarios', 'Usuarios')], max_length=30, verbose_name='Módulo'),
        ),
    ]
