# Generated by Django 6.0.6 on 2026-06-23 01:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('transporte', 'Transporte'), ('recoleccion', 'Recolección'), ('clasificacion', 'Clasificación'), ('procesamiento', 'Procesamiento'), ('mantenimiento', 'Mantenimiento'), ('personal', 'Personal'), ('otro', 'Otro')], default='otro', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoría de Egreso',
                'verbose_name_plural': 'Categorías de Egreso',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría de Ingreso',
                'verbose_name_plural': 'Categorías de Ingreso',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos', to='contabilidad.categoriaegreso')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta_material', 'Venta de material'), ('subsidio', 'Subsidio'), ('donacion', 'Donación'), ('otro', 'Otro')], default='venta_material', max_length=50)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_por_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='contabilidad.categoriaingreso')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
    ]
