# Generated by Django 6.0.6 on 2026-06-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('Metal', 'Metal'), ('Vidrio', 'Vidrio'), ('Plástico', 'Plástico'), ('Papel/Cartón', 'Papel/Cartón'), ('Orgánico', 'Orgánico'), ('Espuma/EPS', 'Espuma/EPS'), ('Otro', 'Otro')], max_length=100, unique=True)),
                ('precio_por_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Precio de Material',
                'verbose_name_plural': 'Precios de Materiales',
                'ordering': ['material'],
            },
        ),
    ]
