# Generated by Django 6.0.6 on 2026-06-24 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_preciomaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaegreso',
            name='tipo',
            field=models.CharField(choices=[('transporte', 'Transporte'), ('clasificacion', 'Clasificación'), ('procesamiento', 'Procesamiento'), ('mantenimiento', 'Mantenimiento'), ('personal', 'Personal'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
