# Generated by Django 6.0.6 on 2026-06-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RutaRecoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la ruta')),
                ('fecha_programada', models.DateField(verbose_name='Fecha programada')),
                ('hora_programada', models.TimeField(blank=True, null=True, verbose_name='Hora programada')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_completada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
            ],
            options={
                'verbose_name': 'Ruta de Recolección',
                'verbose_name_plural': 'Rutas de Recolección',
                'ordering': ['fecha_programada', 'prioridad'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(choices=[('#1b4332', 'Verde oscuro'), ('#1d3557', 'Azul marino'), ('#780000', 'Rojo oscuro'), ('#7b2d8b', 'Morado'), ('#b5451b', 'Naranja oscuro')], default='#1b4332', max_length=20, verbose_name='Color de identificación')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['nombre'],
            },
        ),
    ]
