# Generated by Django 6.0.6 on 2026-06-18 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clasificacion', '0001_initial'),
        ('recoleccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rutarecoleccion',
            name='operador',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Operador asignado'),
        ),
        migrations.AddField(
            model_name='rutarecoleccion',
            name='residuos',
            field=models.ManyToManyField(blank=True, related_name='rutas', to='clasificacion.residuo', verbose_name='Residuos asignados'),
        ),
        migrations.AddField(
            model_name='rutarecoleccion',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='recoleccion.zona', verbose_name='Zona'),
        ),
    ]
