# Generated by Django 6.0.6 on 2026-06-18 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='residuos/')),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('confianza', models.FloatField(default=0)),
                ('resultado_json', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAdministracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_predominante', models.CharField(blank=True, max_length=100)),
                ('materiales', models.JSONField(blank=True, default=dict)),
                ('prioridad', models.CharField(blank=True, max_length=50)),
                ('nivel_prioridad', models.IntegerField(default=6)),
                ('alertas', models.JSONField(blank=True, default=list)),
                ('resultado_grammar', models.JSONField(blank=True, default=dict)),
                ('fecha_procesado', models.DateTimeField(auto_now_add=True)),
                ('residuo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administracion', to='clasificacion.residuo')),
            ],
        ),
    ]
