# Generated by Django 6.0.6 on 2026-06-24 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0001_initial'),
        ('contabilidad', '0002_preciomaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResiduoAceptado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aceptacion', models.DateTimeField(auto_now_add=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0, help_text='Peso estimado del residuo en kg', max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('aceptado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingreso_generado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residuo_origen', to='contabilidad.ingreso')),
                ('residuo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aceptado', to='clasificacion.residuo')),
            ],
            options={
                'verbose_name': 'Residuo Aceptado',
                'verbose_name_plural': 'Residuos Aceptados',
                'ordering': ['-fecha_aceptacion'],
            },
        ),
    ]
