# Generated by Django 6.0.6 on 2026-06-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0002_residuoaceptado'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoadministracion',
            name='peso_medio_kg',
            field=models.FloatField(default=0, help_text='Peso medio estimado por el Grammar Engine (kg) para el material predominante'),
        ),
    ]
